apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniflux
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/redelokal/infraestrutura.git
    targetRevision: HEAD
    path: apps/apps/miniflux

    helm:
      valuesObject:
        ingress:
          certManager:
            issuerName: letsencrypt

  destination:
    namespace: miniflux
    name: in-cluster
  syncPolicy:
    automated: 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true