apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-01
  namespace: postgresql
spec:
  instances: 3
  storage:
    size: 40Gi
    storageClass: vultr-block-storage-hdd-retain
  managed:
    roles:
      - connectionLimit: -1
        ensure: present
        inherit: true
        login: true
        name: app
        superuser: true
        createdb: true
        createrole: true

      - name: miniflux
        connectionLimit: -1
        ensure: present
        inherit: true
        login: true
        superuser: false
        passwordSecret:
          name: miniflux-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: miniflux
  namespace: postgresql
spec:
  name: miniflux
  owner: miniflux
  cluster:
    name: postgresql-01