apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniflux
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/redelokal/infraestrutura.git
    targetRevision: HEAD
    path: charts/miniflux

    helm:
      valueFiles:
      - $values/app/envs/common/miniflux.yaml
      - $values/app/envs/{{ .Values.env }}/miniflux.yaml

  destination:
    namespace: miniflux
    name: in-cluster
  syncPolicy:
    automated: 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true