apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/redelokal/infraestrutura
    path: charts/databases/postgresql
    chart: postgresql
    targetRevision: 0.1.0
  destination:
    namespace: postgresql
    name: in-cluster
  syncPolicy:
    automated: 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true