apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:

  - repoURL: https://movetokube.github.io/postgres-operator
    chart: ext-postgres-operator
    targetRevision: 2.0.0
    helm:
      valueFiles:
      - $values/app/envs/common/postgres-operator-values.yaml
      - $values/app/envs/{{ .Values.env }}/postgres-operator-values.yaml
    
  - repoURL: 'https://github.com/redelokal/infraestrutura'
    targetRevision: main
    ref: values

  destination:
    namespace: postgres-operator
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true