apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-01
  namespace: postgresql
spec:
  instances: 3
  storage:
    size: 40Gi
    storageClass: vultr-block-storage-hdd-retain
  managed:
    roles:
    - name: app
      login: true
      superuser: true

